#!/bin/bash
# scripts/proto-gen.sh

set -e

PROTO_DIR="packages/proto"
OUT_DIR="$PROTO_DIR/generated"

echo "Note: Java proto should be generated by Gradle in apps/server-sc"

echo "Generating protobuf code..."
mkdir -p $OUT_DIR/{python,go}

# Python
echo "RUN: Python..."

if ! command -v python3 &> /dev/null; then
    echo "❌ python3 not found"
    exit 1
fi

if ! python3 -c "import grpc_tools" 2>/dev/null; then
    echo "⚠️  grpcio-tools not found. Run: pip3 install grpcio-tools"
    exit 1
fi

python3 -m grpc_tools.protoc \
  --proto_path=$PROTO_DIR \
  --python_out=$OUT_DIR/python \
  --grpc_python_out=$OUT_DIR/python \
  $PROTO_DIR/*.proto

touch $OUT_DIR/__init__.py

# Fix relative import in Python grpc code
# This is a known issue: https://github.com/protocolbuffers/protobuf/issues/1491
find "$OUT_DIR/python" -name "*_grpc.py" -exec sed -i 's/^import .*_pb2 as/from . &/' {} \;

echo "OK: Python protobuf generated"

# Go
echo "RUN: Go..."

if ! command -v protoc &> /dev/null; then
    echo "❌ protoc not found"
    exit 1
fi

export PATH="$PATH:$(go env GOPATH)/bin"

if ! command -v protoc-gen-go &> /dev/null; then
    echo "   Installing protoc-gen-go..."
    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
fi

protoc \
  --proto_path=$PROTO_DIR \
  --go_out=$OUT_DIR/go \
  --go_opt=paths=source_relative \
  --go-grpc_out=$OUT_DIR/go \
  --go-grpc_opt=paths=source_relative \
  $PROTO_DIR/*.proto

if [ ! -f "$OUT_DIR/go/go.mod" ]; then
    echo "   Creating go.mod..."
    cat > $OUT_DIR/go/go.mod << 'EOF'
module mediaserver/proto

go 1.25.5

require (
    google.golang.org/grpc v1.78.0
	google.golang.org/protobuf v1.36.10
)
EOF

    cd $OUT_DIR/go
    go mod tidy
    cd - > /dev/null
fi

echo "OK: Go protobuf generated"

echo "OK: Protobuf generation complete"
echo "Check $OUT_DIR for result"