package grpc

import (
	"context"
	"errors"
	"fmt"
	"log/slog"

	"speaky-media/internal/core"
	pb "mediaserver/proto"

	"github.com/pion/webrtc/v4"
)

// MediaServiceServer implements the ControlService gRPC interface.
type MediaServiceServer struct {
	pb.UnimplementedControlServiceServer
	manager *core.Manager
}

// NewServer creates a new MediaServiceServer.
func NewServer(manager *core.Manager) *MediaServiceServer {
	return &MediaServiceServer{
		manager: manager,
	}
}

// CreateRoom creates a new media room.
func (s *MediaServiceServer) CreateRoom(ctx context.Context, req *pb.CreateRoomRequest) (*pb.CreateRoomResponse, error) {
	// Create room (ID is auto-generated by Manager if we pass empty, or we can use UUID here)
	// Manager.GetOrCreateRoom takes an ID.
	// For now, let's assume HostID + some randomness or just let Client dictate ID?
	// core.Manager.GetOrCreateRoom(id)

	// Phase 4 simplification: Use host_id as room_id logic or generate one.
	// Let's generate a simple one if not strictly required.
	// But `GetOrCreateRoom` expects an ID.
	// Phase 4 simplification: Use host_id as room_id directly.
	// This allows the Client to dictate the RoomID by passing it as HostId.
	roomID := req.HostId

	room, err := s.manager.GetOrCreateRoom(roomID)
	if err != nil {
		return nil, fmt.Errorf("failed to get or create room: %w", err)
	}

	slog.Info("CreateRoom called", "roomID", room.ID, "hostID", req.HostId)

	return &pb.CreateRoomResponse{
		RoomId: room.ID,
	}, nil
}

// JoinRoom handles the WebRTC signaling to join a room.
// It accepts an SDP Offer, processes it, waits for ICE gathering, and returns an SDP Answer.
func (s *MediaServiceServer) JoinRoom(ctx context.Context, req *pb.JoinRoomRequest) (*pb.JoinRoomResponse, error) {
	slog.Info("JoinRoom called", "roomID", req.RoomId, "userID", req.UserId)

	// Delegate to Manager
	// Manager.Join accepts (roomID, userID, offerSDP) -> returns (answerSDP, error)
	// But we need to ensure "Gathering Complete" logic inside Session or here?
	// core.Session.HandleOffer currently just returns CreateAnswer.
	// If we want "Answer with Candidates", we need to modify Session or handle it there.

	// Let's modify core.Session logic in future to wait for gathering?
	// Or we can rely on Trickle from Server if we implement SubmitIceCandidate client-side pull?
	// Protocol doesn't have Pull.
	// So we MUST wait for gathering in core.

	answerSDP, err := s.manager.Join(req.RoomId, req.UserId, req.SdpOffer)
	if err != nil {
		if errors.Is(err, core.ErrRoomNotFound) {
			return nil, fmt.Errorf("room not found: %s", req.RoomId)
		}
		return nil, fmt.Errorf("failed to join room: %w", err)
	}

	return &pb.JoinRoomResponse{
		SdpAnswer: answerSDP,
	}, nil
}

// SubmitIceCandidate handles Trickle ICE from client -> server.
func (s *MediaServiceServer) SubmitIceCandidate(ctx context.Context, req *pb.SubmitIceCandidateRequest) (*pb.SubmitIceCandidateResponse, error) {
	room, err := s.manager.GetRoom(req.RoomId)
	if err != nil {
		return &pb.SubmitIceCandidateResponse{Success: false}, fmt.Errorf("room not found")
	}

	session, exists := room.GetSession(req.UserId)
	if !exists {
		return &pb.SubmitIceCandidateResponse{Success: false}, fmt.Errorf("session not found")
	}

	// Pion's AddICECandidate expects Init struct
	candidate := webrtc.ICECandidateInit{
		Candidate:     req.Candidate,
		SDPMid:        &req.SdpMid,
		SDPMLineIndex: uint16Ptr(int(req.SdpMLineIndex)),
	}

	if err := session.AddICECandidate(candidate); err != nil {
		slog.Warn("Failed to add ICE candidate", "error", err)
		return &pb.SubmitIceCandidateResponse{Success: false}, err
	}

	return &pb.SubmitIceCandidateResponse{Success: true}, nil
}

// LeaveRoom handles user departure.
func (s *MediaServiceServer) LeaveRoom(ctx context.Context, req *pb.LeaveRoomRequest) (*pb.LeaveRoomResponse, error) {
	if err := s.manager.Leave(req.RoomId, req.UserId); err != nil {
		slog.Warn("LeaveRoom failed", "error", err)
		return &pb.LeaveRoomResponse{Success: false}, err
	}
	return &pb.LeaveRoomResponse{Success: true}, nil
}

// Helper
func uint16Ptr(i int) *uint16 {
	val := uint16(i)
	return &val
}
